Ensuring TS will compile using > kive@0.8.4 install /Users/james/git/Kive > typings install && tsc; sass --update kive/
├── imagediff (global dev)
├── jasmine (global dev)
├── jasmine-jquery (global dev)
└── jquery (global dev)

kive/pipeline/tests/dialog.tests.ts(20,5): error TS2322: Type '(url: string, ...restArgs: any[]) => JQueryDeferred<{}>' is not assignable to type '{ (url: string, success?: (data: any, textStatus: string, jqXHR: JQueryXHR) => any): JQueryXHR; (...'.
kive/pipeline/tests/dialog.tests.ts(20,5): error TS2322: Type '(url: string, ...restArgs: any[]) => JQueryDeferred<{}>' is not assignable to type '{ (url: string, success?: (data: any, textStatus: string, jqXHR: JQueryXHR) => any): JQueryXHR; (...'.
  Type 'JQueryDeferred<{}>' is not assignable to type 'JQueryXHR'.
    Property 'overrideMimeType' is missing in type 'JQueryDeferred<{}>'.
kive/pipeline/tests/dialog.tests.ts(250,13): error TS2346: Supplied parameters do not match any signature of call target.
kive/pipeline/tests/pipeline_functions.tests.ts(401,13): error TS2346: Supplied parameters do not match any signature of call target.
kive/sandbox/static/sandbox/PipelineRunTable.ts(3,39): error TS2307: Cannot find module '/static/pipeline/pipeline_all'.
kive/sandbox/static/sandbox/view_run.ts(13,8): error TS2307: Cannot find module '/static/pipeline/pipeline_all'.
kive@0.8.4 /Users/james/git/Kive
└─┬ typings@1.4.0
  ├── any-promise@1.3.0
  ├── archy@1.0.0
  ├── bluebird@3.4.6
  ├─┬ columnify@1.5.4
  │ └─┬ wcwidth@1.0.1
  │   └─┬ defaults@1.0.3
  │     └── clone@1.0.2
  ├── has-unicode@2.0.1
  ├── listify@1.0.0
  ├─┬ typings-core@1.6.0
  │ ├── array-uniq@1.0.3
  │ ├─┬ configstore@2.1.0
  │ │ ├─┬ dot-prop@3.0.0
  │ │ │ └── is-obj@1.0.1
  │ │ ├── graceful-fs@4.1.9
  │ │ ├─┬ mkdirp@0.5.1
  │ │ │ └── minimist@0.0.8
  │ │ ├── os-tmpdir@1.0.2
  │ │ ├── osenv@0.1.3
  │ │ ├── uuid@2.0.3
  │ │ └─┬ write-file-atomic@1.2.0
  │ │   ├── graceful-fs@4.1.9
  │ │   ├── imurmurhash@0.1.4
  │ │   └── slide@1.1.6
  │ ├── detect-indent@4.0.0
  │ ├── graceful-fs@4.1.9
  │ ├─┬ has@1.0.1
  │ │ └── function-bind@1.1.0
  │ ├─┬ invariant@2.2.1
  │ │ └─┬ loose-envify@1.2.0
  │ │   └── js-tokens@1.0.3
  │ ├─┬ is-absolute@0.2.6
  │ │ ├─┬ is-relative@0.2.1
  │ │ │ └─┬ is-unc-path@0.1.1
  │ │ │   └── unc-path-regex@0.1.2
  │ │ └── is-windows@0.2.0
  │ ├── lockfile@1.0.2
  │ ├─┬ make-error-cause@1.2.2
  │ │ └── make-error@1.2.1
  │ ├─┬ mkdirp@0.5.1
  │ │ └── minimist@0.0.8
  │ ├── object.pick@1.1.2
  │ ├─┬ popsicle@8.2.0
  │ │ ├─┬ form-data@2.1.1
  │ │ │ └── asynckit@0.4.0
  │ │ └── throwback@1.1.1
  │ ├─┬ popsicle-proxy-agent@3.0.0
  │ │ ├─┬ http-proxy-agent@1.0.0
  │ │ │ └─┬ agent-base@2.0.1
  │ │ │   └── semver@5.0.3
  │ │ └── https-proxy-agent@1.0.0
  │ ├── popsicle-retry@3.2.1
  │ ├── popsicle-rewrite@1.0.0
  │ ├── popsicle-status@2.0.0
  │ ├── promise-finally@2.2.1
  │ ├─┬ rc@1.1.6
  │ │ ├── deep-extend@0.4.1
  │ │ └── ini@1.3.4
  │ ├─┬ rimraf@2.5.4
  │ │ └─┬ glob@7.1.1
  │ │   └── minimatch@3.0.3
  │ ├─┬ sort-keys@1.1.2
  │ │ └── is-plain-obj@1.1.0
  │ ├── string-template@1.0.0
  │ ├── thenify@3.2.1
  │ ├── throat@3.0.0
  │ ├── touch@1.0.0
  │ └── zip-object@0.1.0
  ├─┬ update-notifier@1.0.2
  │ ├─┬ boxen@0.6.0
  │ │ ├── ansi-align@1.1.0
  │ │ ├── cli-boxes@1.0.0
  │ │ ├── filled-array@1.1.0
  │ │ └── widest-line@1.0.0
  │ ├── is-npm@1.0.0
  │ ├─┬ latest-version@2.0.0
  │ │ └─┬ package-json@2.4.0
  │ │   ├─┬ got@5.6.0
  │ │   │ ├─┬ create-error-class@3.0.2
  │ │   │ │ └── capture-stack-trace@1.0.0
  │ │   │ ├─┬ duplexer2@0.1.4
  │ │   │ │ └─┬ readable-stream@2.1.5
  │ │   │ │   └── isarray@1.0.0
  │ │   │ ├── is-redirect@1.0.0
  │ │   │ ├── is-retry-allowed@1.1.0
  │ │   │ ├── is-stream@1.1.0
  │ │   │ ├── lowercase-keys@1.0.0
  │ │   │ ├── node-status-codes@1.0.0
  │ │   │ ├─┬ read-all-stream@3.1.0
  │ │   │ │ └─┬ readable-stream@2.1.5
  │ │   │ │   └── isarray@1.0.0
  │ │   │ ├─┬ readable-stream@2.1.5
  │ │   │ │ └── isarray@1.0.0
  │ │   │ ├── timed-out@2.0.0
  │ │   │ ├── unzip-response@1.0.1
  │ │   │ └─┬ url-parse-lax@1.0.0
  │ │   │   └── prepend-http@1.0.4
  │ │   ├── registry-auth-token@3.1.0
  │ │   └── registry-url@3.1.0
  │ ├── lazy-req@1.1.0
  │ ├── semver-diff@2.1.0
  │ └─┬ xdg-basedir@2.0.0
  │   └── os-homedir@1.0.2
  └── wordwrap@1.0.0 .